#!/bin/sh
#
# look up a package's status in the m68k-all.txt file

#all="alpha arm hppa i386 ia64 m68k mips mipsel powerpc s390 sparc"
#arch=$(echo $QUERY_STRING |cut -f1 -d"_")
#PKG=$(echo $QUERY_STRING |sed -e 's/.*pkg=\([^&]*\).*/\1/')
#PKG=${PKG%%_*}

# apache doesn't like this: (where's header; where's blank line?)

. /home/builddnet/conf.d/database.conf

cat << .
Content-type: text/html

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<html>
<head>
<title>$PKG</title>
</head>
<body bgcolor="#ffffff" text="#000000">
<pre>
.
psql -h $host $database -c "select arch, name, lastseen as \"lastseen at UTC+1\", interval, lastseen + (4* interval) as \"expected at UTC+1\" from status order by arch, name"

echo '</pre></body>'

exit 0

