#!/bin/sh
#
# look up a package's status in the m68k-all.txt file

#all="alpha arm hppa i386 ia64 m68k mips mipsel powerpc s390 sparc"
#all="hppa ia64 m68k"
all=`cat ~younie/unstable/bin/archs`

flavour=$(echo "$QUERY_STRING" |cut -f1 -d"_")
arch=$(echo $QUERY_STRING |cut -f2 -d"_")
PKG=$(echo $QUERY_STRING |sed -e 's/.*pkg=\([^&]*\).*/\1/'|sed -e 's/%2B/+/g')
PKG=${PKG%%_*}

# apache doesn't like this: (where's header; where's blank line?)

cat << .
Content-type: text/html

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<html>
<head>
<title>$PKG</title>
</head>
<body bgcolor="#ffffff" text="#000000">

.
case "$arch" in 
"all" )
    echo "<ul>"
	for i in $all; do
		if [ -z $PKG ];then
    		    echo " ..need a pkg[_vers]"
		else
				echo "<li> $i:"
				echo "<pre>"
				HIT=$(sed -n "/\/${PKG}_/,/^[/a-z0-9A-Z]/p" /home/younie/$flavour/listdir/${i}-all.txt |sed '$d')
        		if [ -z "$HIT" ]; then
            		    echo " $PKG not registered"
		        else
    		            echo "$HIT"
        		fi
				echo "</pre></li><br><p>"
		fi
	done
	echo "</ul>"
	;;
* )
	echo "<pre>"
	if [ -z $PKG ];then
    	    echo " ..need a pkg[_vers]"
	else
    	    HIT=$(sed -n "/\/${PKG}_/,/^[/a-z0-9A-Z]/p" /home/younie/listdir/${arch}-all.txt |sed '$d')
        	if [ -z "$HIT" ]; then
            	    echo " $PKG not registered"
	        else
    	            echo "$HIT"
        	fi
	fi
	echo "</pre>"
	;;
esac


echo '</body>'

exit 0

